apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customservices.sample.javaoperatorsdk
spec:
  group: sample.javaoperatorsdk
  version: v1
  scope: Namespaced
  names:
    plural: customservices
    singular: customservice
    kind: CustomService
    shortNames:
      - cs
  preserveUnknownFields: false
  validation: 
    openAPIV3Schema:
      type: object
      properties:
        name:
          type: string
        spec:
          type: object
          properties:
            testSuite:
              type: string
            service:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
            dependencies:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  image:
                    type: string
        status:
          type: object
          properties:
            ready:
              type: boolean
  subresources:
    status: {}
